# -*- coding: utf-8 -*-
"""P1LAB1_DavisCornelius.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCyrlDnhlBJVuO99LjwmU6AmB06oY9H2
"""

from ast import fix_missing_locations
# Davis Cornelius
# 2/5/2025
# P1LAB1
# Using input and print functions

# Get info from user
f_name = input("enter your fisrt name: ")
l_name = input("enter your last name: ")

# Display greeting to user
print("Hello," , f_name, l_name  + "!", "Welcome to CTI-110🤞🤞🤞")

# using integers
transaction_num = 20
withdraws = 10
deposits = 3

known_tt = withdraws + deposits
unknown_tt = transaction_num - known_tt

print("Total number of transactions is", transaction_num, "and the number of known transaction types is", str(known_tt) + ".")
print("the unknown transaction number is", str(unknown_tt) + ".")

starting_balance = 133333.58
withdrawal = 16555.55
deposit = 500.25

print("starting Balance:", starting_balance)
print("after making withdrawal of", "$" + str(withdrawal))
print("new balance: $" + str (starting_balance - withdrawal))
print()
print()
print()

# By default, the input function assigns user input as strings
cust_name = input("enter first and last name: ")
bank_name = input("bank info: ")
phone_num = input("enter phone number: ")

print("Bank:" , bank_name)
print("Name:" , cust_name)
print("phone:" , phone_num)